### ISSUE TITLE
Install script and root mysql password

### ISSUE THREAD

**Issue by stefaweb** [mailwatch/mailwatch-install-script#36]
Hi @Skywalker-11!

Again me.

During script run, it ask for root mysql password (mariadb).

Unfortunately, I entered a wrong password.

The script ran without error message but at the end no database installed and as well no connection for the GUI.

I have the art of doing stupid things. ;)

It will may be fine to add a check for the mysql password.

**Comment by stefaweb** [comment]
Can may be checked with: `mysqladmin -uroot -pxxxx ping`

**Comment by Skywalker-11** [comment]
done
