### ISSUE TITLE
clamaAV not working after fresh install

### ISSUE THREAD

**Issue by stefaweb** [mailwatch/mailwatch-install-script#41]
Still with fresh Debian Stretch fresh install + mariadb 10.1 installed + postfix installed (not configured).

- clamd was not running just after setup.sh finished to run.
- clamAV not see in GUI in sf_version.php
- clamAV not see in GUI in clamav_status.php

in /var/log/apache2/error.log:

```
mkdir: cannot create directory '/var/spool/MailScanner/incoming': Permission denied
mktemp: failed to create directory via template '/var/spool/MailScanner/incoming/clamav-tmp/tmp.XXXXXXXXXX': Permission denied
ERROR: Option --tempdir requires a non-empty string argument
ERROR: Can't parse command line options
```

**Comment by stefaweb** [comment]
Seems that for Postfix, nothing is done concerning the clamav right.

As I'm new with Postfix, I don't know what should be done.

```
# grep -ri clamav setup.scripts/*
setup.scripts/exim/mailwatch-exim.sh:usermod -a -G "$EximGroup" clamav
setup.scripts/exim/mailwatch-exim.sh:usermod -a -G mtagroup clamav
setup.scripts/exim/mailwatch-exim.sh:if [[ -z $(grep -r "clamav: root" /etc/aliases) ]]; then
setup.scripts/exim/mailwatch-exim.sh:    echo "clamav: root" >> /etc/aliases
setup.scripts/mailscanner/mailwatch-mailscanner.inc:    ask 'Do you want to use Clamav? (y/n)[y]:' useClamav
setup.scripts/mailscanner/mailwatch-mailscanner.inc:    useClamav=${useClamav:-y}
setup.scripts/mailscanner/mailwatch-mailscanner.inc:    useClamav=${useClamav,,}
setup.scripts/mailscanner/mailwatch-mailscanner.inc:    if [ "$useClamav" != "y" ] && [ "$useClamav" != "n" ]; then
setup.scripts/mailscanner/mailwatch-mailscanner.inc:        logprint "Invalid option given for use of Clamav!!!"
setup.scripts/mailscanner/mailwatch-mailscanner.inc:        "$MailScannerTmpDir/MailScanner-$MailScannerVersion/install.sh" "--MTA=$MTA"  "--installClamav=$useClamav" "--installCPAN=$useCpan" "--ignoreDeps=$ignoreDeps" "--ramdiskSize=$ramdiskSize"
setup.scripts/mailwatch/mailwatch-setup-config.inc:#use/install clamav by mailscanner (y/n)
setup.scripts/mailwatch/mailwatch-setup-config.inc:useClamav=

```

**Comment by Skywalker-11** [comment]
Only thing to do is set the value `Virus Scanners = clamav` in MS config files

**Comment by stefaweb** [comment]
clamav works with last code version but:

- clamAV not see in GUI in sf_version.php
- clamAV not see in GUI in clamav_status.php
- very slow when running ms_lint.php in GUI
- still the mkdir error message when running sa_lint.php in GUI

```
Jul 17 12:04:58.107 [27997] dbg: config: mkdir /var/www/.spamassassin failed: mkdir /var/www/.spamassassin: Permission denied at /usr/share/perl5/Mail/SpamAssassin.pm line 1902. | 0.00111
-- | --
Jul 17 12:04:58.107 [27997] dbg: config: using "/etc/MailScanner/spamassassin.conf" for user prefs file
```

**Comment by Skywalker-11** [comment]
Probably https://github.com/mailwatch/MailWatch/pull/1060/files thats not yet in v1.2.9

**Comment by stefaweb** [comment]
You are right.

Works with last code from mailwatch.

![capture d ecran 2018-07-17 a 13 28 05](https://user-images.githubusercontent.com/12907102/42814834-cd76a1cc-89c5-11e8-91d8-dd32b1356d2d.png)
![capture d ecran 2018-07-17 a 13 29 48](https://user-images.githubusercontent.com/12907102/42814838-d00e83be-89c5-11e8-83b5-619755e4a53e.png)

For geoip update, the /opt/mailwatch/public/temp directory doesn't have the good right after setup.sh. GUI can't write.

The mkdir error message is still here.

**Comment by stefaweb** [comment]
Solved.
