### ISSUE TITLE
Whishlist: add stuff for systemd when mariaDB is used

### ISSUE THREAD

**Issue by stefaweb** [mailwatch/mailwatch-install-script#43]
Install /etc/systemd/system/mailscanner.service.d/override.conf if mariaDB is used according to the documentation:

Using MailWatch with MailScanner and Systemd
https://docs.mailwatch.org/install/installing.html

**Comment by Skywalker-11** [comment]
Shouldn't be necessary with current MS: https://github.com/MailScanner/v5/blob/master/common/usr/lib/MailScanner/systemd/ms-systemd

Already corrected in docs dev https://github.com/mailwatch/mailwatch-docs/commit/83c29aa08685de18b09af4db27e37871bf5a93ab#diff-8db532db01d6e2be7b5b3b3d393d0908
https://github.com/mailwatch/mailwatch-docs/blob/develop/_posts/2017-03-23-installing.md

**Comment by stefaweb** [comment]
Thanks.
