### ISSUE TITLE
/etc/apache2/sites-available/mailwatch.conf not configured after install

### ISSUE THREAD

**Issue by stefaweb** [mailwatch/mailwatch-install-script#44]
Still with fresh Debian Stretch fresh install + mariadb 10.1 installed + postfix installed (not configured).

In /etc/apache2/sites-available/mailwatch.conf:

`ServerName MWHOSTNAME` not configured with hostname during setup.sh (two times).

**Comment by Skywalker-11** [comment]
https://github.com/mailwatch/mailwatch-install-script/blob/develop/setup.sh#L64-L65
😁

**Comment by stefaweb** [comment]
When I try a code the bugs get scared. 😄
