### ISSUE TITLE
Whishlist: Check prerequisites when launching setup.sh

### ISSUE THREAD

**Issue by stefaweb** [mailwatch/mailwatch-install-script#45]
I don't know if this is done, but can setup.sh check prerequisites to accept to run the script.

- MTA installed and running
- database engine installed and running
- right entries in /etc/apt/sources.list (unrar from non-free)

And more if needed.

**Comment by Skywalker-11** [comment]
MTA can be installed during the setup (done by mailscanner if not already installed)
DB will also be installed if not existant

unrar could be done but it sounded like @shawniverson may want to do that in MS

**Comment by stefaweb** [comment]
Ok, I was thinking that we need these.
