### ISSUE TITLE
pyzor doesn't work after install

### ISSUE THREAD

**Issue by stefaweb** [mailwatch/mailwatch-install-script#52]
I got this running ms_lint.php from GUI after a fresh install.

`pyzor: check failed: internal error, python traceback seen in response`

**Comment by Skywalker-11** [comment]
Not sure but I thing there was something that pyzor does not work on local mails.
Testing with https://wiki.apache.org/spamassassin/UsingPyzor seems to work

**Comment by stefaweb** [comment]
Yo, I forgotten that.
I checked. It works.
