### ISSUE TITLE
clamav take a very long time

### ISSUE THREAD

**Issue by stefaweb** [mailwatch/mailwatch-install-script#56]
It take a very long time. Don't know why. No error.

![capture d ecran 2018-07-17 a 18 33 40](https://user-images.githubusercontent.com/12907102/42831980-27af7266-89f0-11e8-8a52-46b4a8a1d8d7.png)

These processes run during ms_lint.php.

```
www-data  4607  3844  0 18:45 ?        00:00:00 sh -c sudo /usr/sbin/MailScanner --lint 2>&1
root      4608  4607  0 18:45 ?        00:00:00 sudo /usr/sbin/MailScanner --lint
postfix   4609  4608 91 18:45 ?        00:00:05 /usr/bin/perl -U -I /usr/share/MailScanner/perl /usr/sbin/MailScanner --lint
```

**Comment by Skywalker-11** [comment]
Maybe its realy clamav thats way slower than clamd. I haven't tried comparing these. Always used clamav until now. How was the CPU consumption while doing that?

**Comment by ghost** [comment]
I'm using clamd and am seeing this...

![image](https://user-images.githubusercontent.com/6255179/42838476-ee650cee-89ce-11e8-9cc9-0cb771d4e540.png)

**Comment by stefaweb** [comment]
Definitively.

I switched back to clamd as on my prod server.

 0.19 instead of 39... (between 28 and 45)

```
MailScanner.conf says "Virus Scanners = clamd" | 0.00192
-- | --
Found these virus scanners installed: clamd | 1.21363
=========================================================================== | 5.0E-5
Filename Checks: Windows/DOS Executable (1 eicar.com) | 0.29424
Other Checks: Found 1 problems | 0.05792
Virus and Content Scanning: Starting | 0.00065
Clamd::INFECTED:: Eicar-Test-Signature :: ./1/eicar.com | 0.19041
Virus Scanning: Clamd found 1 infections | 0.78917
Infected message 1 came from 10.1.1.1 | 0.00267
Virus Scanning: Found 1 viruses | 0.00124
=========================================================================== | 0.03494
```

Commands to activate clamd.
```
Virus Scanners = clamd
Clamd Socket = /var/run/clamav/clamd.ctl
Clamd Lock File = /var/run/clamav/clamd.pid
Clamd Use Threads = no
Monitors for ClamAV Updates = /var/lib/clamav/*.cld /var/lib/clamav/*.cvd
```

with clamscan:
```
MailScanner.conf says "Virus Scanners = clamav" | 0.00223
Found these virus scanners installed: clamd | 1.02344
=========================================================================== | 7.0E-5
Filename Checks: Windows/DOS Executable (1 eicar.com) | 0.31675
Other Checks: Found 1 problems | 0.07459
Virus and Content Scanning: Starting | 0.00081
1.message: Eicar-Test-Signature FOUND | 39.10909
./1/eicar.com: Eicar-Test-Signature FOUND | 0.00363
Virus Scanning: ClamAV found 2 infections | 1.19134
Infected message 1 came from 10.1.1.1 | 0.0025
Virus Scanning: Found 2 viruses | 0.00089
=========================================================================== | 0.02199
```

We can consider to switch setup.sh to clamd. ;)

**Comment by stefaweb** [comment]
What do we do with this?

"clamscan very slow" seems a very popular keyword on Google. 😂

**Comment by Skywalker-11** [comment]
I give it a try and then adjust the setup. 

I realy just had one case when I started with MS und MW on a realy low traffic and realy low performance machine aka. Raspberry Pi where clamd just was using up too many resources all the time and clamav was a better choice as it was only using it when there were actually mails inbound 😁

**Comment by stefaweb** [comment]
Raspberry!!!
By the 64bits version. 
My son built a cluster of 12 with Kubernetes and all the stuff. A little AWS at home 😃

**Comment by Skywalker-11** [comment]
It seems to work if I just change Virus Scanners to `clamd`.

The `Monitors for ClamAV Updates` doesn't seem to be for `clamd`
https://www.mailscanner.info/MailScanner.conf.index.html#Monitors%20for%20ClamAV%20Updates
As for `Clamd Lock File` the file you mentioned doesn't exist on my system.

**Comment by Skywalker-11** [comment]
It's working fine as imap/smtp/MS/MW server. You may only get 3-10 mails/minute scanned depending on the mails you receive and as such there may be a small delay but other than that it is totally working. 

Especially if you are a poor student who doesn't have much money and space and want to get your very own first server its a good way to start and get familiar with linux.

**Comment by stefaweb** [comment]
> As for `Clamd Lock File` the file you mentioned doesn't exist on my system.
Same. We can trash. 
No longer exist on Stretch.

> For `Monitors for ClamAV Updates`
Same. We can trash.
Seems a scorie from old config using clamavmodule.

> Clamd Socket
Same. We can trash. The default is ok.
/etc/MailScanner/MailScanner.conf:Clamd Socket = /var/run/clamav/clamd.ctl

> For ` Clamd Use Threads = no`
Have a look. Some say put it to NO is better but the manual is clear.

```
 If MailScanner is running on a system with more then 1 CPU core (or
    more than 1 CPU) then you can set "Clamd Use Threads" to "yes" to
    speed up the scanning, otherwise there is no advantage and it should
    be set to "no".
```

Test:

With ` Clamd Use Threads = yes` (default)
`Jul 18 17:52:06 antispam MailScanner[6336]: Batch (1 message) processed in 1.14 seconds`
With ` Clamd Use Threads = no`
`Jul 18 17:53:20 antispam MailScanner[6972]: Batch (1 message) processed in 1.20 seconds`

**Comment by stefaweb** [comment]
> Especially if you are a poor student who doesn't have much money and space and want to get your very own first server its a good way to start and get familiar with linux.

This one is cheap and works very fine.
https://www.pine64.org/?page_id=7147

**Comment by stefaweb** [comment]
Done.
