### ISSUE TITLE
Contributions from eFa for CentOS/postfix based MailWatch installations

### ISSUE THREAD

**Issue by ghost** [mailwatch/mailwatch-install-script#6]
https://efa-project.org would like to contribute scripts for MailWatch installation on CentOS 6/7 with postfix based installations.

Initial guidance would be needed for contribution, as the scripts will need tailored for generalized MailWatch installations instead of the appliance based installation that comprises eFa.

I can sit back and observe the exim/debian installation as it progresses first.

**Comment by asuweb** [comment]
@shawniverson - thank you sir.  

Your contributions will be extremely welcome - I'm also a centos / postfix guy. 

I think @Skywalker-11 is a postfix user & @stefaweb is an Debian/exim user.

**Comment by stefaweb** [comment]
Welcome!

And a Proxmox + KVM or LXC  user.

**Comment by ghost** [comment]
@stefaweb @Skywalker-11 

This may help with the mailwatch install script.  Feel free to browse for how eFa is configuring some things.  Each of the scripts sets up a component, whether it be mailwatch, mailscanner, etc.  Might give you all some ideas or insight.  If I have some time, I will sit down and compare this install script with the eFa installation scripts and see if we get some synergy going.

https://github.com/E-F-A/v4/tree/master/rpmbuild/SOURCES/eFa-4.0.0
