### ISSUE TITLE
MailScanner config name

### ISSUE THREAD

**Issue by Skywalker-11** [mailwatch/mailwatch-install-script#9]
In which order does MailScanner read the custom configs under conf.d? If it is 0... ,1... , ....... , 9.. , a...., ..... , z... We should use 0mailwatch.conf as config name so that user are able to override our defined values in their custom conf.

**Comment by asuweb** [comment]
I suspect it will be 0, but not 100% sure.

**Comment by stefaweb** [comment]
You're right.
We need 00maiwatch.conf
